d1 = driver.find_elements(By.TAG_NAME,"input")
        d1 = driver.find_elements(By.TAG_NAME, "input")
        d1 = driver.find_elements(By.TAG_NAME, "input")
        d1 = driver.find_elements(By.TAG_NAME, "input")
        print(len(d1))